language: php
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
matrix:
  fast_finish: true
  allow_failures:
     - php: 7.4
install:
  - composer install --no-interaction --prefer-source
script:
  - composer test
after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
